# Generated by Django 2.0.2 on 2018-02-27 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_twist', '0003_auto_20170409_1621'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-start_time']},
        ),
        migrations.AlterModelOptions(
            name='friendrequest',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='invitation',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='customuserdata',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
